### ISSUE TITLE
Phone project structure and others

### ISSUE THREAD

**Issue by andreujuanc** [quark-dev/Phonon-Framework#145]
Hello,

I'm playing around with this project, i can say i really like it. Simple and worked on the first try. (~~I'm looking at you, angular2~~).

I dont want to use vue or riot, but I want to keep files as much component-like as I can.

My questions:
 1- How can I move the activity events to the template ? 
 2- It is safe to try to use it with RactiveJS?

Thanks!

**Comment by andreujuanc** [comment]
Solved it by modifying the source.
First, i added instance to the current page, not just the name and setted in all places where currentPage is also set.
```
return {
      currentPage: currentPage,
      currentPageObject: currentPageObject,
```

With this then on the template:

```
var activity = phonon.navigator().currentPageObject.activity;
activity.onCreate(function () {
      console.log('on create');
});
```

It didnt work when activity callback is not passed so:

```
if(typeof callback === 'function' || typeof callback === 'object') {
    page.activity = new Activity(callback);
} else {
    page.activity = new Activity({});;
}
```

Maybe it can be done in a sexier way, but i dont know much this project (just 1 hour playing with it). It would be nice to implement this officialy.

What do you guys think?

**Comment by andreujuanc** [comment]
Maybe i will change it a bit, dont like to set it like that. 

I was thinking on coding currentPageObject as a method or something, so it calls getpage.

**Comment by Qathom** [comment]
HI @andreujuanc,

Thank you for your idea, I think it is nice to implement it so that using a page scope is not mandatory like the following:
```js
phonon.navigator().on(...}, function(activity) {
    activity.onCreate(function() {})
})
```

**Comment by Qathom** [comment]
@andreujuanc , I added this for the next version (1.2.8):

```js
phonon.navigator().onPage('home').addEvent('create', function () {
})
phonon.navigator().onPage('home').addEvent('ready', function () {
})
phonon.navigator().onPage('home').addEvent('transitionend', function () {
})
phonon.navigator().onPage('home').addEvent('hidden', function () {
})
phonon.navigator().onPage('home').addEvent('tabchanged', function (tabNumber) {
})
phonon.navigator().onPage('home').addEvent('close', function (api) {
	api.close()
})
phonon.navigator().onPage('home').addEvent('hashchanged', function (param) {
	console.log('params ' + param)
})
```

**Comment by andreujuanc** [comment]
Great!  But I think getting the current page was a bit more elegant. Since now writing .onPage('home') makes it prone to error when writing the page name. For example if i change the page name, i have to completely search for places to rename.

Still is better than it was before. Did you tried this new solution by using it on a script tag inside the template?


Another topic: Why is it necesary to write the pagename as tag on template? <pagename> 
Is it because you can have multiple templates on a file? or just to make stuff easier? 

I think it would be faster just to take it out if posible. As with your solution, it would make things easier: one file = one template. And not to write multiple times the page name.

Also, I would like to implement for myself,(and if it works i would post it) a convention based naming for templates files, so i dont have to write the page name and filename. Just have it optional if the filename is diferent than pagename. You already have a base url, it would take nothing to do this.

I really like this project, and please forgive me if im too annoying.

Cheers!

**Comment by Qathom** [comment]
Re @andreujuanc,

Thank you very much for your suggestions! You are not annoying at all ;)

_Great! But I think getting the current page was a bit more elegant. Since now writing .onPage('home') makes it prone to error when writing the page name. For example if i change the page name, i have to completely search for places to rename._

Yes, but the problem is that without page names, we need to set for example an UID for pages..Were you thinking about "a page object" alternative? For example:
```js
var aPage = phonon.navigator().on({page: 'home', ...}
aPage.on('create', function () {

})
```

_Still is better than it was before. Did you tried this new solution by using it on a script tag inside the template?_

Yes, the `<script>` tag is evaluated once the page template has been loaded. For example:
```html
<mypage class="app-page">
    <header class="header-bar">
        <h1 class="title title-left">My Page</h1>
    </header>
    <div class="content">
         ....
    </div>
</mypage>

<script>
    document.on('pagecreated', function(event) {
        console.log('event.detail.page created')
    });
    phonon.navigator().onPage('mypage').addEvent('create', function () {
        console.log('on create')
    })
</script>
```

_Another topic: Why is it necesary to write the pagename as tag on template? 
Is it because you can have multiple templates on a file? or just to make stuff easier?_

It was inspired by Riot tags for compatibility. But maybe you are right, it is not necessary mandatory with other frameworks such as Riot. I need to run some tests to confirm this..


_Also, I would like to implement for myself,(and if it works i would post it) a convention based naming for templates files, so i dont have to write the page name and filename. Just have it optional if the filename is diferent than pagename. You already have a base url, it would take nothing to do this._

This is a great idea and feature! You are welcome to make a pull request :)
I will keep in mind this idea!

**Comment by andreujuanc** [comment]
I agree. If keep it for compatibilities, then it's ok. But as you said, it's good idea to just require it if working with Riot.

Just to report: Phonon works flawlessly with Ractive.js (not reactive, jesus those namings).

This is my side project, so this weekend if everything goes ok i will try to implement last feature (naming conventions). Now im fighting some ugly sql procedures that did 0.02 + 0.02 = 0.03  Im not kidding!! Hope doesnt take much to solve.

Cheers!

**Comment by Qathom** [comment]
I'll add Ractive to the list so :)
Good luck with your projects!

**Comment by andreujuanc** [comment]
@Qathom mate, i added the convention based naming path. I wont do pull yet, need more testing, let me know if it follows your programming guide (or if it looks sexy ) .

https://github.com/andreujuanc/Phonon-Framework/commit/aa31d78a3c8c4a6350b97ecebbc50465c3910558#diff-712364b0c799cdedfacfb35b259a3faf

Cheers

**Comment by andreujuanc** [comment]
btw, how do you  test the project? I was doing it using any browser and F5 xD but has some problems with CORS and meh, got sleepy. do you use any node server? express? Or just simply cordova?

thanks

**Comment by Qathom** [comment]
Hi @andreujuanc,

First of all, **thank you** for working on Phonon! :). It looks sexy indeed.

For the tests: it depends.
If it concerns the UI, I try on many devices and some emulators, but here it concerns the core or "backend" of Phonon. I normally run tests by checking with other frameworks in the `examples` folder.
Fur the future, I planned to add a unit testing framework in order to test the different APIs.
I am currently working with a simple apache server and for testing on Cordova, I use the [Ripple emulator](https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc).

**Comment by andreujuanc** [comment]
ok great.

**Comment by Qathom** [comment]
Re @andreujuanc,

I just merged your pull request. Thanks again! :)
I just found out that pagetwo.html was missing, so I added it.
The new option has been added in the [docs](http://phonon.quarkdev.com/docs/).
