### ISSUE TITLE
refresh after insert elements based on a template

### ISSUE THREAD

**Issue by gbtux** [quark-dev/Phonon-Framework#166]
Hi,
First, thanks to the Phonon's Team.

I've a little problem with tabs when i inject them after 'ready'.

A quick example : 

```
<actualite class="app-page">
     <header ... > .............</header>
     <div class="content" id="content-actualite">
     </div>
     <script type="text/x-handlebars-template" id="actusList">
        <button class="floating-action icon icon-facebook active btn-facebook"></button>
        <button class="floating-action icon icon-twitter active btn-twitter" style="left:15px;"></button>
        <nav class="tabs header-tabs hidden">
            <div class="tab-items">
                {{#actus}}
                    <a class="tab-item" >{{id}}</a>
                {{/actus}}
            </div>
            <div class="tab-indicator"></div>
        </nav>
        <div class="content" data-tab-contents="true" data-disable-swipe="false" data-tab-default="1" id="list_actus">
        {{#actus}}
            <div class="tab-content">
                <div class="card" style="margin-top: 14%">
                    <div class="card-image">
                        <img src="img/test/wayfarer.jpg">
                    </div>
                    <div class="card-content">
                        <h3>{{titre}}</h3>
                        <p>{{actualite}}</p>
                    </div>
                    <div class="card-action">
                      <a href="#"  data-slide="prev" data-i18n="text: previous"></a>
                      <a href="#" class="pull-right" data-slide="next" data-i18n="text: next"></a>
                    </div>
                    <a class="right carousel-control" href="" role="button" data-slide="next">
                        <span class="icon-circle-right" aria-hidden="true"></span>
                    </a>
                    <a class="left carousel-control" href="" role="button" data-slide="prev">
                        <span class="icon-circle-left" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        {{/actus}}
        </div>
    </script>
</actualite>
<script>
    phonon.navigator().onPage('actualite').addEvent('ready', function () {
        realApp.wait();
        phonon.ajax({
            method: 'GET',
            url: realApp.baseAPI + '/actualites',
            crossDomain: true,
            dataType: 'json',
            contentType: 'application/json',
            headers: {
                'X-AUTH-TOKEN': localStorage.getItem('token')
            },
            success: function(data){
                var template = Handlebars.compile($('#actusList').html());
                realApp.stopWaiting();
                var res = { actus : data };
                $('#content-actualite').html(template(res));
                phonon.tab().refreshTabs('actualite'); //new function here
            },
            error: function(res, flagError, xhr){
                realApp.stopWaiting();
                phonon.alert('Un problème est apparu');
            }
        });
    });
</script>
```

Ajax is OK and html is correctly produced and inserted in the page.
But Tabs are not operative :(

To "refresh" and activate tabs, i made a little function "refreshTabs" in tabs JS component (based on the 1.2.1 version / setCurrentTab is the original) : 

```
        /**
     * Changes the tab indicator
     * @param {String} pageName
     * @param {Number} tabNumber
     */
    var setCurrentTab = function(pageName, tabNumber) {
        if(typeof pageName !== 'string') {
            throw new Error('The first argument must be a string, ' + typeof tabNumber + ' given');
        }
        if(typeof tabNumber !== 'number') {
            throw new Error('The second argument must be a number, ' + typeof tabNumber + ' given');
        }

        updateIndicator(pageName, tabNumber);
    };

    //gbtux
    var refreshTabs = function(pageName) {
        var pageEl = document.querySelector(pageName);
        var tabsEl = pageEl.querySelector('[data-tab-contents="true"]');

        if(tabsEl) {
            setupTabs(pageName, pageEl, tabsEl);
        }
    }

    /**
     * For every mounted page, initizalize tabs
     */
    document.on('pagecreated', checkForTabs);

    phonon.tab = function() {
        return {
            setCurrentTab: setCurrentTab,
            refreshTabs: refreshTabs
        };
    };
```

So my question : can i do it in another way ?

**Comment by andreujuanc** [comment]
I have had the "same issue" with some other components. And I thought I was alone on this one xD

I would say your solution is fine. I dont use Handlebars but Ractive, and they have more or less the same problem with phonon components. Maybe there is a more decentralised way to do your code, (later in this post i will show how i solved it with Ractive's decorators). 

If you have some free time, let's go on a ride, since  I will use this post to talk about what I have in mind.

Like I said, I use Ractive, and I was planing to code some way to enable refreshing of components setup, without breaking anything!! (for example, subscribing to the same event twice for elements that were created on ready).

Currently components have to be already in DOM when pagecreated is called, since most of components (if not all) are initiated like this:  `document.on('pagecreated', function(evt) ....`

In my case i have to "pollute" some component with something like this:

```
 var accordionDecorator = function(node){
        node.on('tap', onPage);
        return {
            teardown: function () {
                console.log('teardown', node);
            }
        };
    }

    if(Ractive !== 'undefined'){
        Ractive.decorators.accordion = accordionDecorator;
    }
```

Which is the ractive way to do stuff when elements are rendered. So basically it's more or less your case, and maybe we can work together to improve this and find a nice way to do it.

This was ok but I dont want to fill phonon code with Ractive related stuff. So we need to find a way to interface component's code with external plugins.

I think there are two cases:

 1. When components are dynamically and asynchronically (is that a word?) created on pagecreate, its too late for them, and phonon already setup components up.
 2. Time after pagecreated and everything, elements are created in the DOM and obviously if they have any component code it wont get initialised. (ontransitionend, but does get called on first load)

On issue number one, i found that calling some new event instead of pagecreated, it worked with some limitations.

If we can find a solution for 2nd issue, first one will be fixed anyways.

Need to be aware that what tab component has, accordion doesnt, which is exposure via phonon instance:,` phonon.tab =... `

We need to start exposing all components. and then:

//for me
phonon.extensions.ractive = new PhononRactiveExtension();
//for you
phonon.extensions.dynamicDOM =  PhononDynamicDOMExtension(); //NICE NAME xD
 
That way phonon could be aware of extensions behavior and code can be centralised and not colliding with eachother's, ( like riot is doing now xD )

**Comment by Qathom** [comment]
Hi @gbtux and @andreujuanc,

Thank you for using Phonon and finding a solution with the missing of support for dynamic tabs.
I
You are both right. Tabs are initialized when the `onCreate` event is called, so if you render your template in this callback, the tabs won't be setup.
With the latest release, I added `phonon.tab().init('pagename')` in order to setup dynamic tabs.

Please, tell me if it works for your use!

**Comment by gbtux** [comment]
Hi @Qathom ,

Happy new year ;)
Thx for your reply (and sorry for my late late answer :/ ).
Works perfectly for me (1.3.4) !

As @andreujuanc said, perhaps add this feature to other components.

Production in 1 week !
BR //
