### ISSUE TITLE
blank page: class app-active not set

### ISSUE THREAD

**Issue by bdedardel** [quark-dev/Phonon-Framework#240]
Hi,

At bootstrap, function *onBeforeTransition* stop at : 
```
if(!started) phonon.dispatchGlobalReady();
```
Indeed, callback is undefined in *onReady* : 
```
phonon.onReady = function(callback) {
	    if (callback == null) {
	        console.error('phonon::onReady callback is null');
	        return;
	    } else if(typeof this.callback == "undefined") {
	        console.error('phonon::onReady callback is undefined'); // <-------- this case
	        return;
	    }
	    console.debug('phonon::onReady callback=',JSON.stringify(callback));
		readyCallbacks.push(callback);
	};
```
... and *app-active* class is never set on the main page... 

### My env

- Linux
- Firefox
- Vue 2.2.6
- Phonon 1.4.5
- Webpack

**Comment by bdedardel** [comment]
Error comes from side panels. See modified pizza-app-with-vue in attachment.

[pizza-app-with-vue-src.zip](https://github.com/quark-dev/Phonon-Framework/files/882154/pizza-app-with-vue-src.zip)

**Comment by bdedardel** [comment]
Hi,

Did you reproduce this issue ?
I'm blocked on this problem and hope that my example would help to find a solution.

Regards
Benjamin

**Comment by John-Henrique** [comment]
Can you show your Phonon config?

At this moment I have access only by phone, so can't see your example file.

**Comment by bdedardel** [comment]
I just took the *Phonon-Framework-master/examples/pizza-app-with-vue* and changed some src files to show the issue.

**Comment by qathom** [comment]
Hello @bdedardel,

Thank you for opening this issue.
I updated the [example with VueJS2](https://github.com/quark-dev/Phonon-Framework/tree/master/examples/pizza-app-with-vue).
With Angular and Vue, you need to add the attribute `data-alias="page-name"` because Phonon reads the tag name which can not be used with virtual DOM.

Instead of doing this:
```
html
<home data-page="true">...</div>
```

You need to do the following:
```
html
<div data-page="true" data-alias="home">...</div>
```

In VueJS, there is a simpler way by getting the component name:
```
html
<div data-page="true" :data-alias="$options.name">...</div>
```

Hope it helps! Please, reopen this issue if it does not work for you.
