### ISSUE TITLE
Demo can not be shown on chrome mobile

### ISSUE THREAD

**Issue by cyberiaa** [quark-dev/Phonon-Framework#264]
Thank you for your amazing job,

I just tested kitchen sink on both Android 4.4 and 5.1 (chrome app). Only white screen will be shown.  However, it works correctly on Chrome Desktop.

**Comment by stevenroh** [comment]
Hello,

Same problem for me on Chrome 61.0.3163.98 on Android and also in Safari iOS.

On Chrome Desktop (win) 62.0.3202.62, I've a white screen with this error `Uncaught SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (phonon.js:1952)`
![phonon](https://user-images.githubusercontent.com/1651603/31689597-37e00916-b390-11e7-9560-810db379d4b6.png)

Caused by `jsonCache = JSON.parse(xhr.responseText);`

**Comment by qathom** [comment]
Hello @cyberiaa and @stevenroh,

Thank you for opening this issue.
It has been fixed.
