### ISSUE TITLE
Angularjs

### ISSUE THREAD

**Issue by paulhovey** [quark-dev/Phonon-Framework#3]
Is it possible to use angularjs with phonon?  If so, is there an example anywhere?  I couldn't find any documentation anywhere about it.  Cheers!

**Comment by Qathom** [comment]
Hello,

There is no support for AngularJS yet.
The next release will register Phonon components as modules for AngularJS.
If you have some ideas or suggestions for this, you are welcome :)

**Comment by sahalswappo** [comment]
Maybe give opportunity to disable anything not related to angular will be ok . please make it awesome in angularjs :+1:

**Comment by Qathom** [comment]
Since the v1.0.0, Phonon plays well with AngularJS. The default hashprefix (#!) is supported (as an option). Page routes can be defined like this: #!/pagename/something-else/

Please see the example in the "examples" directory:
https://github.com/quark-dev/Phonon-Framework/tree/master/examples

If you still have some suggestions in mind, it will be a pleasure to read them! :+1:
