### ISSUE TITLE
app.changePage -> activity.onHashChanged no params

### ISSUE THREAD

**Issue by tanwaniniranjan** [quark-dev/Phonon-Framework#31]
So, I am changing the page with - app.changePage("pagetwo", "prosciutto");
on the next page - activity.onHashChanged(function(pizza) { console.log(pizza); }); gives no data

in fact even on refreshing on this new hash, activity.onHashChanged(function(pizza) { console.log(pizza); }); gives no data.

More precise repro conditions: when the page is opened the first time, it wont work, but if I use the back button and then come back to this page, it does work.

**Comment by tanwaniniranjan** [comment]
for now, a dirty fix is:

activity.onReady(function() {
    app.changePage(window.location.hash.split("#!")[1].split("/")[0], window.location.hash.split("#!")[1].split("/")[1]);
});

**Comment by Qathom** [comment]
Hi,

Thank you for reporting this error.
The problem: the page scope (activity callback) was called in the OnCreate callback, but since the release 1.0.2, the onHash callback is called before every page callbacks. So indeed, there was a "conflict".
I just fixed this, please let me know if it still doesn't work :)

**Comment by tanwaniniranjan** [comment]
That was quick!
And it worked like a charm! :)
Thank you!
