### ISSUE TITLE
Page html context

### ISSUE THREAD

**Issue by metacatdud** [quark-dev/Phonon-Framework#5]
Hi, 
First of all. congrats on the new release! Looks awesome. I just started using your framework 3 weeks ago. This last release kicks ass! I'm a big fan of Vanilla JS so I really enjoy the look and feel oh Phonon! It's a bit tricky thought , it'd doesn't have backward compatibility but is ok!

I have one question though, how to retrieve the page object from within the activity?

Awesome job guys!

**Comment by Qathom** [comment]
Hi,

Thank you for your support! This gives motivation :)
I am happy to learn that you use Phonon for your projects!

You are right, there is no backward compatibility as the code and the API's structure have been partially rewritten.. we preferred to clean the old structure instead of creating "shortcuts" to support old releases. Normally, the update does not take too long to put in place! The page object (DOM element?) is not passed as an argument in v1.0.0 because it can be
e used with document.querySelector('page-name'). This is not definitive , so I need your advice.

**Comment by metacatdud** [comment]
Uhmm. I thought so! I used the same thing. I'm currently  writing a wrapper over phonon because how it is now is more of a librarie suite then a full fledged framework. This is awesome because you can use only the libs you want!

What i'm trying to polish right now is the following format
```
phonon.module('module_name', function(ph) {    
   //code goes here
   //ph - internal facade for module "module_name" with phonon libraries and stuff such as html context and what ever else it's needed here :)
   - or -
   //ph - will have only two instructions require and instance

    //v1
    var ajax = ph.ajax({/* config */});

    //v2
    var ajax = ph.require('ajax');
    // if case
    var instance = ph.instance('some_lib_with_instance'); //This of course will held the local scope of "module_name ;)"  

    // on both v1 and v2
    ph.name -> "module_name"
    ph.DOM -> html component of this module
})
```

What do you think?

**Comment by Qathom** [comment]
Interesting format!

According to me:

** If ph is an internal facade**

It is a good practice only if Phonon is fully loaded (phonon.js).

**If ph has only two instructions**

It is great only if the core of Phonon is loaded (phonon-core.js).

According

**Comment by Qathom** [comment]
We also love flexibility :).
Interesting format! Which JS libraries do you use?
I am not sure to understand your goals, but according to me:

** If ph is an internal facade**

It is a good practice only if Phonon is fully loaded (phonon.js) and fully used (also there is no need to include other modules).

**If ph has only two instructions**

It is great only if the core of Phonon is loaded (phonon-core.js). If your module (module_name) contains functions that are not called directly during the module loading, this way is better than the other one because it reduces the number of required modules when it is loaded. On the other hand, inside functions you need to require them. For example, the function named "doGet" needs to require the ajax module.

**Comment by metacatdud** [comment]
I'm using Vanilla JS if you ask me what library i use. If you ask me what phonon libs i'm using, for now only navigation, i18n and ajax. 

I don't quite like the way i18n lib is working as it does multiple requests if I have dynamic content on a page. I'm thinking o loading the language file only once on app load/device ready and change it only when needed?!

The structure i mentioned in the comment above is to have a some sort of modular architecture:
- home
  - dashboard
  - loading
- auth
  - register
  - login
etc

So it will be something like:

```
phonon.module('home_dashboard', function(ph) {    
    
    /**
     * Main home module object
     */
    var Home  = {
    
    };
     [...]
    //---Private code goes above this line
    ph.navigation().on({
            page: 'home',
            content: 'home/home.html',
            preventClose: false
    }, function(activity) {
            activity.onCreate(Home.ui.create);
            activity.onReady(Home.ui.ready);
        });
})
// And so on...
phonon.module('home_loading', function(ph) {  })

phonon.module('auth_login', function(ph) {  })
phonon.module('auth_register', function(ph) {  })
phonon.module('authe_recover', function(ph) {  })
```

**Comment by Qathom** [comment]
You will get a beautiful code with your idea :)
It is true that it is not efficient to load the same JSON file several times.
I just fixed this! Thank you for your comment.
Do not forget to call:
```javascript
phonon.updateLocale('new-language');
```
In order to update the language **and** your HTML views automatically.

**Comment by metacatdud** [comment]
:) Thanks, I'll try to share it as fast as I finish my project and thanks for this quick fix on language.
One think though... where to call this instruction? Do I need to do something before running this instruction?

**Comment by Qathom** [comment]
Nope, this instruction is not required, but it is useful only if you want to change the current app language.
For example, when the user changes the default app language manually (if the user has a preference for the app language).
This utility function will update the value of the current language and your HTML views containing data-i18n attributes.
