### ISSUE TITLE
Component sidepanel - support same sidepanel on all pages

### ISSUE THREAD

**Issue by Kroesss** [quark-dev/Phonon-Framework#90]
I would like to propose an enhancement to the sidepanel component.

I would like to use this component to create my applications main menu. However, the sidepanel-div requires that it is stated on what page it exists ("data-page"). That prevents the use of this component as a menu.

Perhaps this required attribute could be made optional. Then you could use it to have the current behaviour, but omit it when you would like the panels available on all pages.

**Comment by John-Henrique** [comment]
:+1: 

@Kroesss this currently is a limitation of Phonon as you can see in #67 issue, but is really a nice enhacement.

**Comment by Kroesss** [comment]
Okay, I thought that was the case. Perhaps this can be something that can be put on the wish-list for a future version :)

Thanks for the fast reply!

**Comment by oksiquatzel** [comment]
Hi,

we tried to get same side-panel work on every loaded template page. We added this little code to the phonon.js part for side-panel to get this to work

    phonon.updatePageTarget = function(newTarget) {
        var spEls = document.querySelectorAll('.side-panel');
        var i = spEls.length - 1;

        for (; i >= 0; i--) {

            var el = spEls[i];
            el.setAttribute('data-page',newTarget);
        }

        var i = sidePanels.length - 1;
        var pageEl = document.querySelector(newTarget);

        for (; i >= 0; i--) {

            var sb = sidePanels[i];
            sb.snapper.settings({
                element: pageEl
            });
            sidePanels[i] = sb;
        }
        render();
    }

In this Code we update the data-page attribute for every .side-panel to the new one and
the element settings of every snapper object to the new one. 
We also call the render function again because this function is called by the event pageopened, and we are changing the target after that event is called.

on page navigation we call the phonon.updatePageTarget with the new page 

    activity.onReady(function() {
        phonon.updatePageTarget("pagetwo");
    });

maybe the code needs some improvements.

Best Regards 
Oksi

**Comment by Qathom** [comment]
Hi @oksiquatzel,

Nice suggestion! I mixed your code with the already defined `render` function.
Side panels are now supporting many pages. With the same attribute **data-page**, you can add several pages separated by a comma like the following: `data-page="home, pagetwo"`.

**Comment by oksiquatzel** [comment]
Hi @Qathom
i found a little problem to the changes you made.

The Problem is in addition with snap.js backdrop part and your changes 

     sb.snapper.settings( {element: pageEl} );

in side-panel part.

Because of your changes the snapper.settings.element is changed now between createBackdrop and removeBackdrop and the removeBackdrop function can't found the backdrop element any more and we get a node notfound error

To fix this, i changed the removeBackdrop part of snap.js 
to

            removeBackdrop: function() {
                if(backdrop) {
                    // Set backdrop to null immediately
                    var _backdrop = backdrop;
                    backdrop = null;

                    var closed = function () {
                        _backdrop.classList.remove('fadeout');
                        // Changed to remove backdrop from its parent and not from the current snap element
                        _backdrop.parentNode.removeChild(_backdrop);
                        // settings.element.removeChild(_backdrop);
                        _backdrop.off(phonon.event.transitionEnd, closed);
                    };

                    _backdrop.classList.add('fadeout');
                    _backdrop.on(phonon.event.transitionEnd, closed);
                }
            },

i tried to change the element after the removeBackdrop part, but it does not work.
Maybe you have a better solution for this?
Should i post this also on github /jakiestfu/Snap.js/ ??

**Comment by oksiquatzel** [comment]
Hi @Qathom 

i have found another problem with your integration and android. (ios i did'nt have tested)
in the phonon.onReady part of sidepanels you set document.body as default element for the snapper object. This does'nt seem to work. The Menü items in the Sidepanel are not touchable anymore in android. The window.hashchange function is'nt triggered.
My solution is to set the first found data-page as the default one.

			for (; j < l; j++) {
				var _page = page[j].trim();
                if(j == 0){
                    var pageEl = document.querySelector(_page);
                }
				_pages.push(_page)
			}

            // Options
            var options = {
                element: pageEl,
                //element: document.body,
                disable: (disable === null ? 'none' : disable),
                hyperextensible: false,
                touchToDrag: false,
                maxPosition: el.clientWidth,
                minPosition: -(el.clientWidth)
            };

I tried to set null instead, but it also doesn't seems to work.

Regards
Oksi
