### ISSUE TITLE
Search bar setup

### ISSUE THREAD

**Issue by Emethium** [quark-dev/Phonon-Framework#98]
Greetings gentleman.

I was willing to add a search bar in one of my application's pages to easily access specific items on a long long list that I added below. I was able to check how to spawn a search bar in Phonon's docs, but I couldn't find out how to make it work with other structures.

Therefore, how could I make a search bar look for items inside a list in the same page?

**Comment by John-Henrique** [comment]
Can you show example?

**Comment by Qathom** [comment]
Hello @Emethium,

Do you use a MVVM pattern like RiotJS, VueJS, Angular, .. ?
I think the best way to accomplish your task is to create a **filter** for your list of items.

Let's call a variable `searchValue` which contains what the users wants to search (onkeyup => update its value). On each value change, call the method or function (depending of the context) called `seachFilter(searchValue)`. This function should return the specific items concerning the search value.

Example of design (this code has not been tested):
```javascript
var searchValue = '' // init

document.querySelector('.search-input').on('keyup', function (event) {
    searchValue = event.target.value
})

function seachFilter(search) {
    // rules for your filter
    return array
}

var dataToShow = searchFilter()
// update view (HTML)
```

I **really recommend** you to use a MVVM pattern because it updates your view according your model (data).

**Comment by Emethium** [comment]
Thanks for the quick reply, @Qathom.

I really wasn't using anything besides what Phonegap and Phonon natively provided me, but I'll surely follow your recommendations. My question was in disbelief as I thought that what I needed had already been written in Phonon's framework JavaScript files.

But now I've got a pretty good idea what I should do next, it was really helpful.

Forgive me if this wasn't really a repository issue, but I deeply thank you for the answer.

**Comment by Qathom** [comment]
It can be a feature if Phonon can help to accomplish something concerning the UI, but for your case, a loop made with a design pattern (for the dynamic list) suits what you want to do. :)

**Comment by Emethium** [comment]
I see! I got it working now, thanks!
